### ISSUE TITLE
Getting duplicate images (seed not incrementing to account for batch size)

### ISSUE THREAD

**Issue by jk-niersbach** [cmdr2/stable-diffusion-ui#123]
Generating several images at a time on a GTX 1660 Super on Win10. Images have started doubling up - the 2nd and subsequent image in each batch will be duplicated at the start of the next batch. Suggests that seed incrementation isn't working correctly. 

It looks like it is incrementing the global seed by 1 each time, rather than by batch size. See [truncated command line output.txt](https://github.com/cmdr2/stable-diffusion-ui/files/9532236/command.line.output.txt) (generating 12 images, 4 at a time).

Also not sure that the seed number displayed in the web GUI (upper right hand corner of each image) is correct.

Problem didn't exist for the first 500 or so images.

**Comment by cmdr2** [comment]
Thanks, will check that. Are you running the latest version? v2.08? This was fixed recently, but it's possible there's a different bug that's causing this for you.

**Comment by jk-niersbach** [comment]
Thanks for the response. Version is `v2.08 (beta)`. I tried fixing it locally by changing it to use `opt_seed += batch_size` but I think it pulls fresh code each time it's started.

Also I note the seed label is the same for each image in a batch. I wonder if this is because it uses `imgSeedLabel.innerHTML = 'Seed: ' + seed` without incrementing inside the `for (let idx in res.output) {` loop?

**Comment by Althorion** [comment]
I can confirm that I have the same issue.

**Comment by RocketPop** [comment]
I just ran a set of 300 images, 3 at a time and I have 3 duplicates of every image as well. I'm on 2.09

**Comment by jk-niersbach** [comment]
Duplicate image generation issue fixed for me on v2.10 (listed as v2.1).

The seed number displayed on each image is still the same for all images in each batch (although this is a minor issue).

**Comment by cmdr2** [comment]
Both the issues have been fixed as of a few versions ago.
